### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pattern'

### ISSUE THREAD

**Issue by rgaiacs** [landscapeio/pylint-django#108] opened 2017-12-18 12:09 UTC
Travis CI is falling for me in another project because of

~~~
$ python -m pylint lowfat
Using config file /home/travis/build/softwaresaved/lowfat/pylintrc
Traceback (most recent call last):
  File "/opt/python/3.5.4/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.5.4/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pylint/lint.py", line 1312, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pylint/lint.py", line 495, in load_plugin_modules
    module.register(self)
  File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pylint_django/plugin.py", line 22, in register
    start = name_checker.config.const_rgx.pattern[:-2]
AttributeError: 'NoneType' object has no attribute 'pattern'
~~~

Any suggestions of what can be causing it?

**Comment by asifpy** [comment] 2017-12-18 12:41
What version of `pylint` are you using? I had similar issue with the latest `pylint==1.8`, and `pylint-django` doesn't seems to compatible with latest pylint.

Try to downgrade the `pylint`, and then test it

**Comment by rgaiacs** [comment] 2017-12-18 15:18
I try to downgrade pylint to a early version but I encounter other problems. Thanks for the help. Feel free to close this issue.

**Comment by christianmlong** [comment] 2017-12-18 18:35
Downgrading to pylint 1.7.5 fixes it for me. 

`pip install 'pylint>=1.7,<1.8'`

```
pylint              1.7.5
pylint-django       0.7.2
pylint-plugin-utils 0.2.6
```
Python 3.6.3 installed via Homebrew.

**Comment by pcharasala** [comment] 2017-12-18 21:12
I have the same issue.
My Pylint is Pylint 1.8.1

**Comment by pcharasala** [comment] 2017-12-18 21:19
@christianmlong Thank you somuch!
I have been struggling since morning. Finally your hint helped me.

**Comment by renatoliveira** [comment] 2017-12-18 22:39
While downgrading to pylint 1.7.5 temporarily fixes this issue, it does present other errors (like https://github.com/PyCQA/pylint/issues/1609 which are fixed with pylint 1.8+ I believe).

I have a project that is using Django 2.0 and I've been using pylint-django with it. Some days ago I configured Travis CI and today when I added pylint to the command list I found this very issue. 😉 

Build log can be found here: https://travis-ci.org/renatoliveira/notto/builds/318305203

Using:
- Python 3.6.3 (64-bit) on Windows 10
- Pylint 1.7.5
- Pylint-django 0.7.2

When Pylint is upgraded to 1.8.1, I get the AttributeError mentioned by @rgaiacs as well.

**Comment by JonHerr** [comment] 2017-12-19 16:06
seems there was some breaking changes with setup
name_checker.config str() output for pylint versions
using pylint 1.8.1
`
{
    'const_rgx': None,
    'include_naming_hint': False,
    'argument_rgx': None,
    'bad_names': ('foo','bar','baz','toto','tutu','tata'),
    'good_names': ('i','j','k','ex','Run','_','qs'),
    'name_group': (),
    'argument_naming_style': 'snake_case',
    'method_rgx': None,
    'function_naming_style': 'snake_case',
    'class_rgx': None,
    'attr_rgx': None,
    'module_naming_style': 'snake_case',
    'const_naming_style': 'UPPER_CASE',
    'module_rgx': None,
    'class_naming_style': 'PascalCase',
    'class_attribute_naming_style': 'any',
    'attr_naming_style': 'snake_case',
    'inlinevar_rgx': None,
    'class_attribute_rgx': None,
    'function_rgx': None,
    'property_classes': ('abc.abstractproperty',),
    'variable_naming_style': 'snake_case',
    'variable_rgx': None,
    'method_naming_style': 'snake_case',
    'inlinevar_naming_style': 'any'
}
`
using pylint 1.7
`
{
    'inlinevar_name_hint': '[A-Za-z_][A-Za-z0-9_]*$',
    'method_name_hint': '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$',
    'module_rgx': re.compile('(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'),
    'attr_rgx': re.compile('(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$'),
    'argument_rgx': re.compile('(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$'),
    'class_name_hint': '[A-Z_][a-zA-Z0-9]+$',
    'good_names': ('i','j','k','ex','Run','_','qs'),
    'class_attribute_name_hint': '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$',
    'class_attribute_rgx': re.compile('([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'),
    'inlinevar_rgx': re.compile('[A-Za-z_][A-Za-z0-9_]*$'),
    'property_classes': ('abc.abstractproperty',),
    'bad_names': ('foo','bar','baz','toto','tutu','tata'),
    'class_rgx': re.compile('[A-Z_][a-zA-Z0-9]+$'),
    'variable_rgx': re.compile('(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$'),
    'function_rgx': re.compile('(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$'),
    'const_rgx': re.compile('(([A-Z_][A-Z0-9_]*)|(__.*__))$'),
    'const_name_hint': '(([A-Z_][A-Z0-9_]*)|(__.*__))$',
    'include_naming_hint': False,
    'function_name_hint': '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$',
    'variable_name_hint': '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$',
    'method_rgx': re.compile('(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$'),
    'attr_name_hint': '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$',
    'module_name_hint': '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$',
    'name_group': (),
    'argument_name_hint': '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$'
}
`

**Comment by cookieY** [comment] 2018-01-04 09:33
I have the same issue too

python 3.6.3

pylint 1.8.1

**Comment by cristianocca** [comment] 2018-01-04 22:49
When can we expect a fix for this? Had to update pylint and just got caught by this

**Comment by hajotka** [comment] 2018-01-05 22:33
I'm also affected by this issue. Going back to 1.7.5 causes other issues as mentioned above.

**Comment by wli** [comment] 2018-01-11 02:38
if anyone else is struggling with this, jambonrose pointed me in the right direction with his commit (https://github.com/jambonsw/django-improved-user/commit/4efdea783fdab0edce3c7fcfe5f9321cfdba208c)

Upgrade to `pylint==1.8.1` causes `AttributeError: 'NoneType' object has no attribute 'pattern'`. `astroid==1.6.0` causes the `Unused variable '__class__' (unused-variable)` error. You'll need to pin/downgrade both to have a working environment.

```
astroid==1.5.3
pylint==1.7.5
```

**Closed** 2018-01-18 14:16 UTC

**Comment by hajotka** [comment] 2018-01-19 08:04
@atodorov : Awesome! Any idea when the next release will come?

**Comment by atodorov** [comment] 2018-01-19 08:17
@hajotka very soon. Maybe even today.

**Comment by rafidka** [comment] 2018-01-20 04:34
It doesn't sound like this issue is resolved, so not sure why it is marked as closed?

**Comment by ecstaticpeon** [comment] 2018-04-23 15:19
@atodorov Hello, the issue seem to have come back in 0.11 with Pylint 1.8.4 or even 1.8.2. Version 0.10.1 is fine.

**Comment by atodorov** [comment] 2018-04-23 20:07
@ecstaticpeon open a new issue for that with the code that reproduces it.

**Comment by ecstaticpeon** [comment] 2018-04-24 12:55
@atodorov Actually it looks like it was something else in my environment. Sorry for the false alarm!

**Comment by indreshverma** [comment] 2022-05-16 10:16
AttributeError: 'NoneType' object has no attribute 'pattern'
facing this issue, i tried and tested all above hints but nothing is working. 
using python3.7,
Django==3.2.13
djangorestframework==3.13.1
graphene==2.1.8
graphene-django==2.15.0
