### ISSUE TITLE
Parameters differ from overridden 'save' method

### ISSUE THREAD

**Issue by rgaiacs** [landscapeio/pylint-django#94] opened 2017-04-26 11:14 UTC
I have 

~~~
class Claimant(models.Model):

    ...

    def save(self, *args, **kwargs):
        ...

        super(Claimant, self).save(*args, **kwargs)
~~~

and I'm getting

~~~
$ grep django pylintrc 
load-plugins=pylint_django
$ python -m pylint --version
__main__.py 1.7.1, 
astroid 1.5.2
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
$ python -m pylint lowfat   
************* Module lowfat.models
W:279, 4: Parameters differ from overridden 'save' method (arguments-differ)

------------------------------------------------------------------
Your code has been rated at 9.98/10 (previous run: 9.98/10, +0.00)
~~~

Line 279 is

~~~
    def save(self, *args, **kwargs):
~~~

Am I doing something wrong?

**Comment by yashLadha** [comment] 2017-05-23 07:07
Try to use 
```
def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None): 
```

**Comment by alexkahn** [comment] 2017-07-12 18:04
That's a decent work around but for this specific case, the django [docs](https://docs.djangoproject.com/en/dev/topics/db/models/#overriding-predefined-model-methods) show us a way (not necessarily _the_ way) to override a `save` method. In the case of this plugin, I would like to be able to either mark the line as not wanting that particular rule applied or have it issue a warning that I should make an explicit setting to ignore that rule in the case of `save` and `delete` on implementations of models.Model.

**Comment by atodorov** [comment] 2018-01-22 21:57
You should be able to disable this warning by adding `# pylint: disable=W:279` as done in the commit by @Frost. The actual definition of  `save()` in Django is as shown by @yashLadha.

As to why Django documents the preferred way of overriding using *args and **kwargs I can only speculate that it is because of future compatibility. However this seems wrong to me. At the very least how is one supposed to know what parameters does such an overriden method take? 

IMO pylint_django is doing what it is supposed to do. If you'd like it different simply disable the warning. Closing as wontfix.

**Closed by atodorov** 2018-01-22 21:57 UTC

**Comment by jsmedmar** [comment] 2018-04-08 14:46
I think `**kwargs`  only should not raise the warning. That isn't that the purpose of `**` anyways?

**Comment by ivancarrancho** [comment] 2018-09-14 21:16
If is django version more than 2* 
and the issue is in the listview,
should be: `def get_context_data(self, *, object_list=None, **kwargs):`

**Comment by lokesh1729** [comment] 2019-01-15 05:22
adding `# pylint: disable=W0221` is working...

**Comment by schumannd** [comment] 2019-12-06 14:06
I don't think this fixes the issue, does it? The rule itself is useful, so disabling it for the whole project is not a good solution IMO

**Comment by jonathan-golorry** [comment] 2020-01-01 09:10
This is an open issue in pylint, not specific to pylint-django: https://github.com/PyCQA/pylint/issues/1482

@schumannd Commenting `# pylint: disable=W0221` or `# pylint: disable=arguments-differ` should disable the check only for the commented line.

**Comment by gitaarik** [comment] 2020-05-04 18:50
I find the error message useful when you don't use `*args, **kwargs`, but when I do use it, I use it because I don't want to bother about the arguments, and yes, for backwards compatibility.

It would be nice if you could set an option so that the error won't show up when using `*args, **kwargs`.
