### ISSUE TITLE
Wrong warning if parent model decorated with python_2_unicode_compatible

### ISSUE THREAD

**Issue by mbarrien** [landscapeio/pylint-django#29] opened 2014-09-28 20:34 UTC
If we have models inheriting from one another, and the parent model has a `@python_2_unicode_compatible` decorator while the child fails to define **unicode**, we get a W5101 model-missing-unicode warning, when we should get a W5103 model-no-explicit-unicode warning. Minor, but does affect what pylint disable I should be placing on the code.

**Comment by atodorov** [comment] 2018-01-22 21:37
@mbarrien FYI the root cause of this is that pylint_django only checks decorators directly applied to the model class under direct examination. It does not traverse back to the parent class to see what sort of decorators or unicode methods are there nor does pylint_django keep any reference count of such objects.

Given that we're moving towards Django 2.0 and Python 3 I'm going to close this as wontfix. Feel free to contribute a patch and I will gladly accept it.

**Closed by atodorov** 2018-01-22 21:37 UTC
